name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
      with:
        persist-credentials: false

    - name: Setup Elm
      uses: justgook/setup-elm@v1

    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        node-version: 12.x

    - name: Set yarn
      id: yarn
      run: |
        echo "::set-output name=dir::$(yarn cache dir)"
        echo "::add-path::$(yarn bin)"
        echo "::add-path::$(yarn global bin)"

    - name: Get Yarn cache
      uses: actions/cache@v1.1.0
      id: yarn-cache-exists
      with:
        path: ${{ steps.yarn.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Get node_modules
      uses: actions/cache@v1.1.0
      id: node_modules-cache-exists
      with:
        path: ./examples/node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-

    - name: Install Dependencies
      #if: steps.yarn-cache-exists.outputs.cache-hit != 'true'
      run: |
        yarn
        echo "::add-path::$(yarn bin)"

    - name: Build
      run: |
        elm make src/Main.elm --output=./gh-pages/bundle.js
        elm make src/Main.elm --output=./gh-pages/Main.html
        node build-assets.js
#        elm make src/Main.elm --optimize --output=./gh-pages/bundle.js
#
#    - name: Optimize Javascript Jump
#      uses: ./.github/actions/optimize-js
#      with:
#        file: ./gh-pages/bundle.js
#        transform: ./examples/transform.js


    - name: Building HTML
      env:
        NODE_ENV: production
        BUNDLE_JS: jump.js

      run: posthtml ./gh-pages/index_template.html -o ./gh-pages/index.html -c posthtml.config.js

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages
